# Generated by Django 5.1.3 on 2025-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_comment_profile_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
