# Generated by Django 5.1.3 on 2025-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onlyfans',
            field=models.URLField(blank=True, null=True),
        ),
    ]
